---
name: "Meta Sync labels"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".github/labels.yaml"]

permissions:
  contents: read
  pull-requests: write
  actions: read
  issues: write

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yaml
          token: "${{ secrets.GITHUB_TOKEN }}"
          delete-other-labels: true
