name: "Meta Labeler"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

permissions:
  contents: read # Allow reading repository contents
  pull-requests: write # Allow creating and modifying PRs
  actions: read # Allow reading the actions
  issues: write

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply labels based on changes
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
